# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Building & Pushing Docker Image For candidateflowApi
        services:
          - docker
        script:
          - export IMAGE_NAME=mad33l/candidateflowapi:$BITBUCKET_COMMIT

          # build the Docker image (this will use the Dockerfile in the root of the repo)
          - docker build -f candidateFlowApi/Dockerfile -t $IMAGE_NAME .
          # authenticate with the Docker Hub registry
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          # push the new Docker image to the Docker registry
          - docker push $IMAGE_NAME
    - step:
        name: Building & Pushing Docker Image For atitudeTestAPI
        services:
            - docker
        script:
          - export IMAGE_NAME=mad33l/atitudetestapi:$BITBUCKET_COMMIT
    
              # build the Docker image (this will use the Dockerfile in the root of the repo)
          - docker build -f atitudeTestAPI/Dockerfile -t $IMAGE_NAME .
              # authenticate with the Docker Hub registry
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
              # push the new Docker image to the Docker registry
          - docker push $IMAGE_NAME
    # - step:
    #       name: Deploy to Test/QA
    #       image: samueldebruyn/debian-git
    #       deployment: test
    #       script:
    #             - chmod +x deploy.sh
    #             - ./deploy.sh $BITBUCKET_COMMIT
